{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4a0eda71-e523-4170-8a1f-c6d230bf969c",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "Ans 1- \n",
    "When creating custom exceptions in a programming language, it is common practice to derive them from the base Exception class. \n",
    "The Exception class serves as the foundation for all exceptions in the language, providing a set of common behaviors and\n",
    "functionalities that can be inherited and extended by custom exceptions. \n",
    "Here are a few reasons why we use the Exception class as the base for custom exceptions:\n",
    "\n",
    "Standardization: By deriving custom exceptions from the Exception class, we adhere to a standardized convention followed by the language. \n",
    "This makes our code more consistent and easier to understand for other developers who are familiar with the language's exception hierarchy.\n",
    "\n",
    "Catching and Handling: Exception handling mechanisms in most programming languages typically use catch blocks to capture \n",
    "and handle different types of exceptions. By inheriting from the Exception class, our custom exceptions become part of the same exception \n",
    "hierarchy, allowing us to catch and handle them using a single catch block for all exceptions of the base class.\n",
    "\n",
    "Compatibility: Many libraries and frameworks within the language may expect or work specifically with exceptions derived from \n",
    "the Exception class. By using the same base class, our custom exceptions become compatible with these libraries and frameworks, \n",
    "ensuring consistent behavior and integration within the broader ecosystem.\n",
    "\n",
    "Polymorphism: Inheritance from the Exception class enables polymorphic behavior, allowing our custom exceptions to be treated \n",
    "as instances of the base Exception class. This allows for flexibility in handling exceptions, as we can catch exceptions of the base \n",
    "class type and handle them generically or handle specific custom exceptions individually.\n",
    "\n",
    "Exception Metadata and Methods: The Exception class often provides useful metadata and methods that can be utilized by our custom \n",
    "exceptions. For example, the Exception class might include properties to store error messages, stack traces, error codes, \n",
    "or additional information about the exception. By inheriting from the base class, our custom exceptions can leverage these properties\n",
    "and methods, enhancing their functionality and usefulness.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a56d74ab-c51d-4c50-aa3c-38f11f78c7e8",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy.\n",
    "Ans 2- \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "224ad0dc-8843-462d-850e-8bffa39d4482",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "BaseException\n",
      "    Exception\n",
      "        TypeError\n",
      "            FloatOperation\n",
      "            MultipartConversionError\n",
      "        StopAsyncIteration\n",
      "        StopIteration\n",
      "        ImportError\n",
      "            ModuleNotFoundError\n",
      "            ZipImportError\n",
      "        OSError\n",
      "            ConnectionError\n",
      "                BrokenPipeError\n",
      "                ConnectionAbortedError\n",
      "                ConnectionRefusedError\n",
      "                ConnectionResetError\n",
      "                    RemoteDisconnected\n",
      "            BlockingIOError\n",
      "            ChildProcessError\n",
      "            FileExistsError\n",
      "            FileNotFoundError\n",
      "            IsADirectoryError\n",
      "            NotADirectoryError\n",
      "            InterruptedError\n",
      "                InterruptedSystemCall\n",
      "            PermissionError\n",
      "            ProcessLookupError\n",
      "            TimeoutError\n",
      "            UnsupportedOperation\n",
      "            itimer_error\n",
      "            herror\n",
      "            gaierror\n",
      "            SSLError\n",
      "                SSLCertVerificationError\n",
      "                SSLZeroReturnError\n",
      "                SSLWantWriteError\n",
      "                SSLWantReadError\n",
      "                SSLSyscallError\n",
      "                SSLEOFError\n",
      "            Error\n",
      "                SameFileError\n",
      "            SpecialFileError\n",
      "            ExecError\n",
      "            ReadError\n",
      "            URLError\n",
      "                HTTPError\n",
      "                ContentTooShortError\n",
      "            BadGzipFile\n",
      "        EOFError\n",
      "            IncompleteReadError\n",
      "        RuntimeError\n",
      "            RecursionError\n",
      "            NotImplementedError\n",
      "                ZMQVersionError\n",
      "                StdinNotImplementedError\n",
      "            _DeadlockError\n",
      "            BrokenBarrierError\n",
      "            BrokenExecutor\n",
      "                BrokenThreadPool\n",
      "            SendfileNotAvailableError\n",
      "            ExtractionError\n",
      "            VariableError\n",
      "        NameError\n",
      "            UnboundLocalError\n",
      "        AttributeError\n",
      "            FrozenInstanceError\n",
      "        SyntaxError\n",
      "            IndentationError\n",
      "                TabError\n",
      "        LookupError\n",
      "            IndexError\n",
      "            KeyError\n",
      "                NoSuchKernel\n",
      "                UnknownBackend\n",
      "            CodecRegistryError\n",
      "        ValueError\n",
      "            UnicodeError\n",
      "                UnicodeEncodeError\n",
      "                UnicodeDecodeError\n",
      "                UnicodeTranslateError\n",
      "            UnsupportedOperation\n",
      "            JSONDecodeError\n",
      "            SSLCertVerificationError\n",
      "            Error\n",
      "            UnsupportedDigestmodError\n",
      "            IllegalMonthError\n",
      "            IllegalWeekdayError\n",
      "            ParserError\n",
      "            ClassNotFound\n",
      "            ClipboardEmpty\n",
      "            MessageDefect\n",
      "                NoBoundaryInMultipartDefect\n",
      "                StartBoundaryNotFoundDefect\n",
      "                CloseBoundaryNotFoundDefect\n",
      "                FirstHeaderLineIsContinuationDefect\n",
      "                MisplacedEnvelopeHeaderDefect\n",
      "                MissingHeaderBodySeparatorDefect\n",
      "                MultipartInvariantViolationDefect\n",
      "                InvalidMultipartContentTransferEncodingDefect\n",
      "                UndecodableBytesDefect\n",
      "                InvalidBase64PaddingDefect\n",
      "                InvalidBase64CharactersDefect\n",
      "                InvalidBase64LengthDefect\n",
      "                HeaderDefect\n",
      "                    InvalidHeaderDefect\n",
      "                    HeaderMissingRequiredValue\n",
      "                    NonPrintableDefect\n",
      "                    ObsoleteHeaderDefect\n",
      "                    NonASCIILocalPartDefect\n",
      "                    InvalidDateDefect\n",
      "            MacroToEdit\n",
      "            InvalidFileException\n",
      "            UnequalIterablesError\n",
      "            InvalidVersion\n",
      "            _InvalidELFFileHeader\n",
      "            InvalidWheelFilename\n",
      "            InvalidSdistFilename\n",
      "            InvalidSpecifier\n",
      "            InvalidMarker\n",
      "            UndefinedComparison\n",
      "            UndefinedEnvironmentName\n",
      "            InvalidRequirement\n",
      "                RequirementParseError\n",
      "            InvalidVersion\n",
      "        AssertionError\n",
      "        ArithmeticError\n",
      "            FloatingPointError\n",
      "            OverflowError\n",
      "            ZeroDivisionError\n",
      "                DivisionByZero\n",
      "                DivisionUndefined\n",
      "            DecimalException\n",
      "                Clamped\n",
      "                Rounded\n",
      "                    Underflow\n",
      "                    Overflow\n",
      "                Inexact\n",
      "                    Underflow\n",
      "                    Overflow\n",
      "                Subnormal\n",
      "                    Underflow\n",
      "                DivisionByZero\n",
      "                FloatOperation\n",
      "                InvalidOperation\n",
      "                    ConversionSyntax\n",
      "                    DivisionImpossible\n",
      "                    DivisionUndefined\n",
      "                    InvalidContext\n",
      "        SystemError\n",
      "            CodecRegistryError\n",
      "        ReferenceError\n",
      "        MemoryError\n",
      "        BufferError\n",
      "        Warning\n",
      "            UserWarning\n",
      "                GetPassWarning\n",
      "                FormatterWarning\n",
      "            EncodingWarning\n",
      "            DeprecationWarning\n",
      "                ProvisionalWarning\n",
      "            PendingDeprecationWarning\n",
      "            SyntaxWarning\n",
      "            RuntimeWarning\n",
      "                ProactorSelectorThreadWarning\n",
      "                UnknownTimezoneWarning\n",
      "                PEP440Warning\n",
      "            FutureWarning\n",
      "                ProvisionalCompleterWarning\n",
      "            ImportWarning\n",
      "            UnicodeWarning\n",
      "            BytesWarning\n",
      "            ResourceWarning\n",
      "            DeprecatedTzFormatWarning\n",
      "            PkgResourcesDeprecationWarning\n",
      "        _OptionError\n",
      "        _Error\n",
      "        error\n",
      "        Verbose\n",
      "        Error\n",
      "        SubprocessError\n",
      "            CalledProcessError\n",
      "            TimeoutExpired\n",
      "        TokenError\n",
      "        StopTokenizing\n",
      "        ClassFoundException\n",
      "        EndOfBlock\n",
      "        TraitError\n",
      "        Error\n",
      "        Error\n",
      "            CancelledError\n",
      "            TimeoutError\n",
      "            InvalidStateError\n",
      "        _GiveupOnSendfile\n",
      "        error\n",
      "        Incomplete\n",
      "        TimeoutError\n",
      "        InvalidStateError\n",
      "        LimitOverrunError\n",
      "        QueueEmpty\n",
      "        QueueFull\n",
      "        Empty\n",
      "        Full\n",
      "        ArgumentError\n",
      "        ZMQBaseError\n",
      "            ZMQError\n",
      "                ContextTerminated\n",
      "                Again\n",
      "                InterruptedSystemCall\n",
      "            ZMQBindError\n",
      "            NotDone\n",
      "        PickleError\n",
      "            PicklingError\n",
      "            UnpicklingError\n",
      "        _Stop\n",
      "        ArgumentError\n",
      "        ArgumentTypeError\n",
      "        ConfigError\n",
      "            ConfigLoaderError\n",
      "                ArgumentError\n",
      "            ConfigFileNotFound\n",
      "        ConfigurableError\n",
      "            MultipleInstanceError\n",
      "        ApplicationError\n",
      "        error\n",
      "        TimeoutError\n",
      "        error\n",
      "        ReturnValueIgnoredError\n",
      "        KeyReuseError\n",
      "        UnknownKeyError\n",
      "        LeakedCallbackError\n",
      "        BadYieldError\n",
      "        ReturnValueIgnoredError\n",
      "        Return\n",
      "        InvalidPortNumber\n",
      "        error\n",
      "        LZMAError\n",
      "        RegistryError\n",
      "        _GiveupOnFastCopy\n",
      "        Error\n",
      "            NoSectionError\n",
      "            DuplicateSectionError\n",
      "            DuplicateOptionError\n",
      "            NoOptionError\n",
      "            InterpolationError\n",
      "                InterpolationMissingOptionError\n",
      "                InterpolationSyntaxError\n",
      "                InterpolationDepthError\n",
      "            ParsingError\n",
      "                MissingSectionHeaderError\n",
      "        NoIPAddresses\n",
      "        BadZipFile\n",
      "        LargeZipFile\n",
      "        BadEntryPoint\n",
      "        NoSuchEntryPoint\n",
      "        DuplicateKernelError\n",
      "        ErrorDuringImport\n",
      "        NotOneValueFound\n",
      "        CannotEval\n",
      "        OptionError\n",
      "        BdbQuit\n",
      "        Restart\n",
      "        ExceptionPexpect\n",
      "            EOF\n",
      "            TIMEOUT\n",
      "        PtyProcessError\n",
      "        FindCmdError\n",
      "        HomeDirError\n",
      "        ProfileDirError\n",
      "        IPythonCoreError\n",
      "            TryNext\n",
      "            UsageError\n",
      "            StdinNotImplementedError\n",
      "        InputRejected\n",
      "        GetoptError\n",
      "        ErrorToken\n",
      "        PrefilterError\n",
      "        AliasError\n",
      "            InvalidAliasError\n",
      "        Error\n",
      "            InterfaceError\n",
      "            DatabaseError\n",
      "                InternalError\n",
      "                OperationalError\n",
      "                ProgrammingError\n",
      "                IntegrityError\n",
      "                DataError\n",
      "                NotSupportedError\n",
      "        Warning\n",
      "        SpaceInInput\n",
      "        DOMException\n",
      "            IndexSizeErr\n",
      "            DomstringSizeErr\n",
      "            HierarchyRequestErr\n",
      "            WrongDocumentErr\n",
      "            InvalidCharacterErr\n",
      "            NoDataAllowedErr\n",
      "            NoModificationAllowedErr\n",
      "            NotFoundErr\n",
      "            NotSupportedErr\n",
      "            InuseAttributeErr\n",
      "            InvalidStateErr\n",
      "            SyntaxErr\n",
      "            InvalidModificationErr\n",
      "            NamespaceErr\n",
      "            InvalidAccessErr\n",
      "            ValidationErr\n",
      "        ValidationError\n",
      "        EditReadOnlyBuffer\n",
      "        _Retry\n",
      "        InvalidLayoutError\n",
      "        HeightIsUnknownError\n",
      "        ParserSyntaxError\n",
      "        InternalParseError\n",
      "        _PositionUpdatingFinished\n",
      "        SimpleGetItemNotFound\n",
      "        UncaughtAttributeError\n",
      "        HasNoContext\n",
      "        ParamIssue\n",
      "        _JediError\n",
      "            InternalError\n",
      "            WrongVersion\n",
      "            RefactoringError\n",
      "        OnErrorLeaf\n",
      "        InvalidPythonEnvironment\n",
      "        MessageError\n",
      "            MessageParseError\n",
      "                HeaderParseError\n",
      "                BoundaryError\n",
      "            MultipartConversionError\n",
      "            CharsetError\n",
      "        Error\n",
      "        HTTPException\n",
      "            NotConnected\n",
      "            InvalidURL\n",
      "            UnknownProtocol\n",
      "            UnknownTransferEncoding\n",
      "            UnimplementedFileMode\n",
      "            IncompleteRead\n",
      "            ImproperConnectionState\n",
      "                CannotSendRequest\n",
      "                CannotSendHeader\n",
      "                ResponseNotReady\n",
      "            BadStatusLine\n",
      "                RemoteDisconnected\n",
      "            LineTooLong\n",
      "        InteractivelyDefined\n",
      "        KillEmbedded\n",
      "        Error\n",
      "            NoSuchProcess\n",
      "                ZombieProcess\n",
      "            AccessDenied\n",
      "            TimeoutExpired\n",
      "        _Ipv6UnsupportedError\n",
      "        QueueEmpty\n",
      "        QueueFull\n",
      "        DebuggerInitializationError\n",
      "        ExpatError\n",
      "        Error\n",
      "            ProtocolError\n",
      "            ResponseError\n",
      "            Fault\n",
      "        ParseBaseException\n",
      "            ParseException\n",
      "            ParseFatalException\n",
      "                ParseSyntaxException\n",
      "        RecursiveGrammarException\n",
      "        ResolutionError\n",
      "            VersionConflict\n",
      "                ContextualVersionConflict\n",
      "            DistributionNotFound\n",
      "            UnknownExtra\n",
      "        _Error\n",
      "        UnableToResolveVariableException\n",
      "        InvalidTypeInArgsException\n",
      "    GeneratorExit\n",
      "    SystemExit\n",
      "    KeyboardInterrupt\n",
      "    CancelledError\n",
      "    AbortThread\n"
     ]
    }
   ],
   "source": [
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(' ' * indent + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent + 4)\n",
    "\n",
    "print_exception_hierarchy(BaseException)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "519b2f0c-3569-4b3c-ae2e-1a80799f1902",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "Ans3- \n",
    "In Python, the ArithmeticError class is the base class for exceptions that occur during arithmetic calculations. \n",
    "It encompasses a variety of specific error classes related to arithmetic operations.\n",
    "Here are two common errors defined in the ArithmeticError class along with examples:\n",
    "\n",
    "1.ZeroDivisionError: This error occurs when attempting to divide a number by zero. \n",
    "It is a subclass of ArithmeticError. Division by zero is mathematically undefined because we cannot divide a number by zero.\n",
    "example:-\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a3ed1630-2a91-4559-b76a-1949f0867e5f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "a = 10\n",
    "b = 0\n",
    "\n",
    "try:\n",
    "    result = a / b\n",
    "except ZeroDivisionError as e:\n",
    "    print(\"Error:\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a72325e7-cc38-42c4-97ab-d68ff4132371",
   "metadata": {},
   "outputs": [],
   "source": [
    "2.ValueError: Although ValueError is not a direct subclass of ArithmeticError, \n",
    "it is a commonly encountered error related to arithmetic operations. \n",
    "It is raised when a built-in operation or function receives an argument with the right type but an inappropriate value.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c78f9af5-e7e8-4998-8d48-4e148b219af3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: invalid literal for int() with base 10: 'abc'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    num = int(\"abc\")\n",
    "except ValueError as e:\n",
    "    print(\"Error:\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "82434cb4-d389-4b7d-ad3b-5f8c1bacab9c",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "Ans 4- \n",
    "\n",
    "The 'LookupError' class is used in Python to handle lookup-related errors. \n",
    "It serves as the base class for more specific lookup error classes, \n",
    "such as KeyError and IndexError, which are used to handle specific types of lookup failures.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3b09c054-555b-4506-b880-1edd72881f9f",
   "metadata": {},
   "outputs": [],
   "source": [
    "1.KeyError:\n",
    "\n",
    "It occurs when you try to access a dictionary using a key that doesn't exist in the dictionary.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "124a252a-9965-4669-a949-07f51be664cc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n"
     ]
    },
    {
     "ename": "KeyError",
     "evalue": "'grape'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[10], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m my_dict \u001b[38;5;241m=\u001b[39m {\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mapple\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;241m1\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mbanana\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;241m2\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124morange\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;241m3\u001b[39m}\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28mprint\u001b[39m(my_dict[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mapple\u001b[39m\u001b[38;5;124m\"\u001b[39m])  \u001b[38;5;66;03m# Output: 1\u001b[39;00m\n\u001b[0;32m----> 3\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mmy_dict\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mgrape\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m)  \u001b[38;5;66;03m# Raises a KeyError: 'grape' not found in the dictionary\u001b[39;00m\n",
      "\u001b[0;31mKeyError\u001b[0m: 'grape'"
     ]
    }
   ],
   "source": [
    "my_dict = {\"apple\": 1, \"banana\": 2, \"orange\": 3}\n",
    "print(my_dict[\"apple\"])\n",
    "print(my_dict[\"grape\"])  \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f4cd4d47-4b19-4767-a65a-96f667243f1f",
   "metadata": {},
   "outputs": [],
   "source": [
    "2.IndexError:\n",
    "\n",
    "It occurs when you try to access an element from a sequence (like a list or a string) using an invalid index \n",
    "or when the index is out of range.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "b1800d2f-232b-4b4b-87bd-968fc1f3224f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3\n"
     ]
    },
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[11], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m my_list \u001b[38;5;241m=\u001b[39m [\u001b[38;5;241m1\u001b[39m, \u001b[38;5;241m2\u001b[39m, \u001b[38;5;241m3\u001b[39m, \u001b[38;5;241m4\u001b[39m, \u001b[38;5;241m5\u001b[39m]\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28mprint\u001b[39m(my_list[\u001b[38;5;241m2\u001b[39m])      \u001b[38;5;66;03m# Output: 3\u001b[39;00m\n\u001b[0;32m----> 3\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mmy_list\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m10\u001b[39;49m\u001b[43m]\u001b[49m)     \u001b[38;5;66;03m# Raises an IndexError: list index out of range\u001b[39;00m\n",
      "\u001b[0;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "my_list = [1, 2, 3, 4, 5]\n",
    "print(my_list[2])     \n",
    "print(my_list[10])     \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7fef97f3-aceb-4d28-a319-63903151e4fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "Ans5- \n",
    "\n",
    "In Python, ImportError and ModuleNotFoundError are both exceptions that occur when there is an issue with importing a module or package.\n",
    "\n",
    "1.ImportError: This exception is raised when there is a problem with importing a module or package.\n",
    "It can occur due to various reasons, such as:\n",
    "\n",
    "The module or package we are trying to import does not exist.\n",
    "The module or package is not installed on your system.\n",
    "The module or package is not accessible from the current directory or the directories specified in the Python's module search path.\n",
    "There is a syntax error or other issues within the module or package we are trying to import.\n",
    "When an ImportError is raised, it typically includes a message that provides more details about the specific issue that occurred.\n",
    "\n",
    "2.ModuleNotFoundError: Starting from Python 3.6, the ModuleNotFoundError exception is a subclass of ImportError. \n",
    "It specifically indicates that the module or package you are trying to import could not be found. \n",
    "It is raised when the Python interpreter fails to locate the module or package you specified in the import statement.\n",
    "\n",
    "ModuleNotFoundError is more specific and informative than a general ImportError.\n",
    "It clearly indicates that the module or package you are trying to import does not exist or cannot be found in the directories \n",
    "specified in the module search path."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e53971be-698b-438d-98f3-9529bb09c603",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q6. List down some best practices for exception handling in python.\n",
    "Ans6- \n",
    "When it comes to exception handling in Python, there are several best practices you can follow to write robust and maintainable code. \n",
    "Here are some of the key practices:\n",
    "\n",
    "1.Be specific with exception handling: Catch only the exceptions you expect and handle them appropriately. Avoid using a bare except \n",
    "statement as it can catch unintended exceptions and hide potential issues.\n",
    "\n",
    "2.Use multiple except blocks: If you anticipate multiple types of exceptions, use separate except blocks for each one. \n",
    "This allows you to handle different exceptions differently.\n",
    "\n",
    "3.Handle exceptions gracefully: Provide clear and meaningful error messages when an exception occurs. \n",
    "Users or developers should be able to understand the cause of the exception and take appropriate actions.\n",
    "\n",
    "4.Use finally block for cleanup: If you need to perform cleanup tasks, such as closing files or releasing resources, use a finally block.\n",
    "The code in the finally block will always execute, regardless of whether an exception was raised.\n",
    "\n",
    "5.Don't ignore exceptions silently: Avoid ignoring exceptions without any action. Logging the exception or notifying the\n",
    "appropriate stakeholders can help in identifying and resolving issues.\n",
    "\n",
    "6.Avoid excessive nesting of try-except blocks: Excessive nesting of try-except blocks can make the code harder to read and maintain.\n",
    "Consider refactoring the code to reduce the nesting level and improve readability.\n",
    "\n",
    "7.Reraise exceptions when appropriate: If you catch an exception but cannot handle it properly, consider reraising \n",
    "it using the raise statement. This allows the exception to propagate up the call stack for further handling.\n",
    "\n",
    "8.Use specific exception classes: Whenever possible, use specific exception classes provided by Python or \n",
    "create custom exception classes that inherit from the built-in Exception class. This helps in distinguishing different types of \n",
    "exceptions and handling them accordingly.\n",
    "\n",
    "9.Use context managers for resource management: Context managers, such as with statements, provide a convenient \n",
    "and reliable way to handle resources like files or database connections. They ensure that resources are properly closed or released, \n",
    "even in the presence of exceptions.\n",
    "\n",
    "10.Write unit tests for exception scenarios: Include tests that specifically target exception scenarios to ensure your \n",
    "code behaves as expected when exceptions are raised. Unit tests help in catching and fixing issues early in the development process."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
